swagger: "2.0"
info:
  description: This is the swagger file for scientific calculator
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /scientificcalc
paths:
  /src/driver/scientific_calc/ScientificCalc/addition/{list_add}:
    post:
      operationId: src.driver.scientific_calc.ScientificCalc.addition
      tags:
        - addition
      summary: Read 2 numbers to perform addition operation
      description: Read 2 numbers
      parameters:
        - name: list_add
          in: path
          type: array
          items:
            type: string
          required: true
      responses:
        200:
          description: Successfully performed addition
          schema:
            type: integer
  /src/driver/scientific_calc/ScientificCalc/subtraction/{list_sub}:
    post:
      operationId: src.driver.scientific_calc.ScientificCalc.subtraction
      tags:
        - subtraction
      summary: Read 2 numbers to perform subtraction operation
      description: Read 2 numbers
      parameters:
        - name: list_sub
          in: path
          type: array
          items:
            type: string
          required: true
      responses:
        200:
          description: Successfully performed subtraction
          schema:
            type: integer
  /src/driver/scientific_calc/ScientificCalc/multiplication/{list_mul}:
    post:
      operationId: src.driver.scientific_calc.ScientificCalc.multiplication
      tags:
        - multiplication
      summary: Read 2 numbers to perform multiplication operation
      description: Read 2 numbers
      parameters:
        - name: list_mul
          in: path
          type: array
          items:
            type: string
          required: true
      responses:
        200:
          description: Successfully performed multiplication
          schema:
            type: integer
  /src/driver/scientific_calc/ScientificCalc/division/{list_div}:
    post:
      operationId: src.driver.scientific_calc.ScientificCalc.division
      tags:
        - division
      summary: Read 2 numbers to perform division operation
      description: Read 2 numbers
      parameters:
        - name: list_div
          in: path
          type: array
          items:
            type: string
          required: true
      responses:
        200:
          description: Successfully performed division
          schema:
            type: integer