swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /scientificcalculator
paths:
 /src/driver/scientific_calc/ScientificCalc/var_initialization/{base_no},{power_no}:
    post:
      operationId: src.driver.scientific_calc.ScientificCalc.var_initialization
      tags:
        - x_power_y
      summary: Calculate value for x power y
      description: Calculate value for x power y
      parameters:
        - name: base_no
          in: path
          description: Provides x value
          type: string
          required: true
        - name: power_no
          in: path
          description: Provides y value
          type: string
          required: true
      responses:
        200:
          description: Gives value for x power y
          schema:
            properties:
              output:
                type: integer
