swagger: "2.0"
info:
  description: This is the swagger file for scientific calculator
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /scientificcalc
paths:
 /src/driver/scientific_calc/ScientificCalc/sin_func{angle}:
      post:
        operationId: src.driver.scientific_calc.ScientificCalc.sin_func
        tags:
          - sin
        summary: calculate value for sin
        description: calculate value for sin
        parameters:
          - name: angle
            in: path
            type: string
            description: provide angle value
            required: true
        responses:
          200:
            description: give value for angle
            schema:
              type: number
              items:
                properties:
                  angle:
                    type: integer

