swagger: "2.0"
info:
  description: This is the swagger file for scientific calculator
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /scientificcalculator
paths:
 /src/driver/scientific_calc/ScientificCalc/calculate_cos/{angle}:
    post:
      operationId: src.driver.scientific_calc.ScientificCalc.calculate_cos
      tags:
        - cos
      summary: Calculate value for cos
      description: Calculate value for cos
      parameters:
        - name: angle
          in: path
          description: Provides x value
          type: number
          required: true
      responses:
        200:
          description: Gives value for cos
          schema:
            properties:
              output:
                type: number