swagger: "2.0"
info:
  description: This is the swagger.yml file for scientific calculator
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /ScientificCalculator
paths:
  /src/driver/ScientificCalc/ScientificCalc{number}:
    get:
      operationId: src.driver.scientific_calc.ScientificCalc.trig_cosh
      tags:
        - calculator
      summary: Read a number to find cosh calculation
      description: Read a number
      parameters:
        - name: number
          in: path
          type: string
          description: Number of people to get from people
          required: true
      responses:
        200:
          description: Successfully read people list operation
          schema:
            type: number
            items:
              properties:
                number:
                  type: string