swagger: "2.0"
info:
  description: This is the swagger file for scientific calculator
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api
paths:
  /src/driver/ScientificCalc/ScientificCalc{x_value}:
    get:
      operationId: src.driver.ScientificCalc.ScientificCalc.square_root
      tags:
        - calci
      summary: Read a number to find square root of a number
      description: Read a number to find square root of a number
      parameters:
        - name: x_value
          in: path
          type: string
          description: provide a number
          required: true
      responses:
        200:
          description: Gives the value of square root of number
          schema:
            type: number
            items:
              properties:
                number:
                  type: integer
