swagger: "2.0"
info:
  description: This is the swagger file for scientific calculator
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api
paths:
  /src/driver/ScientificCalc/ScientificCalc{number}:
    get:
      operationId: src.driver.ScientificCalc.ScientificCalc.one_by_x
      tags:
        - calculator
      summary: Read a number to find one by x of a number
      description: Read a number to find one by x of a number
      parameters:
        - name: number
          in: path
          type: string
          description: provide a number
          required: true
      responses:
        200:
          description: Gives the value of one by x of number
          schema:
            type: number
            items:
              properties:
                number:
                  type: integer
